const PROMPTS = [
  // Animals (1-20)
  "A cute golden retriever puppy playing in a flower garden",
  "A majestic tiger walking through snow",
  "A baby elephant wearing a party hat",
  "A red panda sleeping on a tree branch",
  "A white owl flying through a moonlit forest",
  "An arctic fox in northern lights",
  "A hummingbird drinking nectar from tropical flowers",
  "A baby penguin sliding on ice",
  "A chameleon on a rainbow colored branch",
  "A golden eagle soaring above mountain peaks",
  "A family of deer in autumn forest",
  "A playful dolphin jumping over ocean waves at sunset",
  "A lazy cat napping in a sunbeam",
  "A wolf pack running through snowy mountains",
  "A colorful parrot in tropical rainforest",
  "A baby otter floating on its back in a river",
  "A graceful swan on a misty lake at dawn",
  "A cheetah sprinting across African savanna",
  "A wise old tortoise in a zen garden",
  "A firefly-lit meadow with rabbits at dusk",
  // Fantasy (21-40)
  "A magical castle floating in the sky at sunset",
  "A wizard casting colorful spells in a library",
  "A phoenix rising from colorful flames",
  "A dragon made of fire breathing ice",
  "A tiny fairy village inside a giant mushroom",
  "An enchanted forest with glowing trees",
  "A mighty griffin guarding a treasure vault",
  "A unicorn galloping through crystal fields",
  "A dark sorcerer summoning a storm",
  "A magical potion shop with floating ingredients",
  "An ancient tree of life glowing with magic",
  "A crystal dragon in an ice cavern",
  "A fairy queen on a throne of flowers",
  "A magical library with flying books",
  "A portal to another dimension in a forest",
  "A giant walking through misty mountains",
  "An elven city built in massive trees",
  "A witch brewing potions under full moon",
  "A celestial whale swimming through nebula",
  "A haunted mansion with ghostly lights",
  // Cyberpunk & Sci-Fi (41-60)
  "A cyberpunk cat wearing neon sunglasses",
  "An astronaut riding a horse on Mars",
  "A neon-lit Japanese street at midnight with rain",
  "A futuristic city with flying cars at night",
  "A robot painting a landscape on canvas",
  "A cyberpunk samurai in neon rain",
  "A space station orbiting a gas giant",
  "A holographic DJ performing in a nightclub",
  "A mech warrior in a destroyed city",
  "An android discovering flowers for the first time",
  "A neon marketplace in a space colony",
  "A hacker's den with holographic screens",
  "A cyborg geisha in a zen garden",
  "A spaceship landing in a bioluminescent forest",
  "A virtual reality world shattering into pixels",
  "A steampunk airship over London at sunset",
  "A time traveler in ancient Rome with future tech",
  "A glitching digital landscape with matrix code",
  "A bio-mechanical tree growing circuits",
  "A retro futuristic diner on the moon",
  // Nature & Landscapes (61-80)
  "A crystal cave with rainbow light reflections",
  "A beautiful koi fish swimming in a crystal clear pond",
  "A vintage car driving through a sunflower field",
  "A cozy coffee shop on a rainy day, anime style",
  "A cherry blossom garden with a wooden bridge",
  "A dramatic thunderstorm over lavender fields",
  "A hidden waterfall in a tropical jungle",
  "A bioluminescent bay at night with stars",
  "A misty bamboo forest at sunrise",
  "A volcano erupting with lava and lightning",
  "An oasis in the Sahara desert at twilight",
  "A frozen waterfall with ice crystals",
  "A field of tulips under dramatic clouds in Holland",
  "An ancient stone circle under the milky way",
  "A coral reef teeming with colorful fish",
  "A rainbow over Niagara Falls",
  "A peaceful rice terrace at golden hour in Bali",
  "A dense foggy redwood forest with light shafts",
  "A dramatic cliff coastline with crashing waves",
  "A northern lights display over an ice lake",
  // Urban & Architecture (81-100)
  "A steampunk city with flying airships",
  "An underwater city with glowing coral buildings",
  "A futuristic Tokyo with holographic billboards",
  "A Venetian canal at sunset with gondolas",
  "An ancient Greek temple at golden hour",
  "A cozy bookshop on a rainy evening in Paris",
  "A rooftop garden on a skyscraper at sunset",
  "A Christmas market in Prague with snow falling",
  "A neon Chinese temple at night with lanterns",
  "A treehouse village connected by rope bridges",
  "An abandoned train station overtaken by nature",
  "A floating market in Bangkok at sunrise",
  "A medieval castle on a cliff during thunderstorm",
  "A futuristic greenhouse dome on Mars",
  "A colorful favela with street art murals",
  "A Japanese hot spring resort in autumn mountains",
  "An art deco skyscraper at twilight",
  "A underground crystal cathedral",
  "A Victorian music hall with candlelight",
  "A space elevator reaching into the clouds",
  // Food & Still Life (101-120)
  "A magical tea party with floating pastries",
  "A sushi roll that looks like a tiny garden",
  "A chocolate fountain surrounded by strawberries",
  "A birthday cake shaped like a dragon",
  "An ice cream sundae in a fantasy world",
  "A beautiful bento box styled like a painting",
  "A golden waffle house with maple syrup waterfalls",
  "A fruit market with impossibly colorful fruits",
  "A steaming bowl of ramen in a cozy shop",
  "A vintage wine cellar with golden light",
  "A fresh pizza coming out of a brick oven",
  "A cotton candy cloud floating over a carnival",
  "A donut shop where everything is pastel colored",
  "A gingerbread village with candy decorations",
  "A tropical smoothie bar on a beach at sunset",
  "A rustic bread basket in a Tuscan kitchen",
  "A bubble tea with galaxy colored boba",
  "A fondue pot in a Swiss mountain chalet",
  "A matcha dessert on a zen stone plate",
  "A pancake stack as tall as a building in a city",
  // Mythology (121-140)
  "A samurai cat in cherry blossom forest",
  "A mermaid sitting on a rock at moonlight",
  "A wolf howling at a purple aurora sky",
  "A Chinese dragon in clouds with golden scales",
  "A Valkyrie riding a winged horse through storms",
  "Thor summoning lightning from storm clouds",
  "Medusa in a dark temple with stone statues",
  "A Japanese kitsune with nine glowing tails",
  "An Egyptian pharaoh with golden sun behind",
  "A Greek god on Mount Olympus at dawn",
  "A Norse longship sailing through a sea monster",
  "A thunderbird in a stormy sky with lightning",
  "Anubis guarding the gates of the underworld",
  "A centaur archer in a moonlit forest",
  "A Japanese oni in a burning temple",
  "A Celtic warrior queen with mystical sword",
  "A Chinese monkey king on a cloud",
  "A Native American spirit wolf in dreamscape",
  "A Hindu goddess dancing with cosmic energy",
  "A minotaur in an ancient labyrinth",
  // Space (141-160)
  "A galaxy in the shape of a butterfly",
  "An astronaut floating in front of Earth",
  "A rocket launching at sunrise with orange clouds",
  "A space whale swimming through nebula",
  "An alien bazaar on a desert planet",
  "A moonbase with Earth rising in background",
  "Binary sunset on Tatooine-like desert planet",
  "A comet passing over ancient pyramids",
  "An astronaut planting flowers on the moon",
  "A nebula nursery where stars are being born",
  "A black hole warping space and light around it",
  "A floating city in Jupiter's atmosphere",
  "A Mars colony with glass domes and gardens",
  "Saturn's rings viewed from a spaceship cockpit",
  "An interstellar highway with multiple spacecraft",
  "A supernova explosion in vibrant colors",
  "An astronaut discovering alien ruins on Europa",
  "A space elevator seen from orbit",
  "A dyson sphere around a distant star",
  "An orbital battle station at sunrise",
  // Seasons & Weather (161-180)
  "A magical autumn forest with golden leaves falling",
  "A snowy village at Christmas with warm lights",
  "A spring meadow with wildflowers and butterflies",
  "A summer beach with crystal clear turquoise water",
  "A thunderstorm over a wheat field at sunset",
  "A blizzard in a mountain town with cozy cabins",
  "A rainbow after rain in a countryside village",
  "Cherry blossom petals falling on a quiet stream",
  "A tornado touching down on open plains dramatic",
  "A sandstorm in a desert city with camels",
  "Autumn harvest festival in a pumpkin patch",
  "First snowfall in Central Park New York",
  "A monsoon rain in Indian streets with colors",
  "A fog rolling into San Francisco Golden Gate",
  "A heatwave mirage in Arizona desert highway",
  "An ice storm creating crystal coated trees",
  "Spring cherry blossoms in Washington DC",
  "A summer festival with fireworks over a lake",
  "A winter solstice celebration at Stonehenge",
  "An autumn vineyard in Tuscany at golden hour",
  // Characters & Portraits (181-200)
  "A steampunk inventor in a workshop full of gears",
  "A pirate captain on a ghost ship in moonlight",
  "A forest elf with bow and glowing arrows",
  "A detective in 1940s noir style rain scene",
  "A punk rock musician playing electric guitar on fire",
  "A geisha walking through snowy Kyoto streets",
  "A Viking warrior on a cliff overlooking the sea",
  "A ballerina dancing in a field of fireflies",
  "A street artist spray painting a galaxy mural",
  "A chef creating food that transforms into butterflies",
  "A librarian in an infinite magical library",
  "A deep sea diver discovering a sunken treasure",
  "A mountain climber at the summit at sunrise",
  "A photographer capturing the perfect sunset",
  "A musician playing piano in an abandoned cathedral",
  "A surfer riding a giant ethereal wave",
  "A gardener tending to a bonsai tree dragon",
  "A clockmaker in a workshop of magical timepieces",
  "An artist painting a portal to another world",
  "A stargazer with a telescope on a floating island",
];

const VIDEO_PROMPTS = [
  // Animals (1-10)
  "A golden retriever puppy running through a meadow of wildflowers",
  "A majestic tiger walking slowly through falling snow",
  "A baby elephant playing in a puddle of water",
  "A dolphin leaping out of crystal clear ocean waves at sunset",
  "A cat stretching and yawning in a warm sunbeam",
  "A wolf howling on a snowy mountain peak under moonlight",
  "A hummingbird hovering near a vibrant tropical flower",
  "A baby penguin sliding on its belly across ice",
  "A horse galloping along a sandy beach at golden hour",
  "A butterfly emerging from its cocoon in slow motion",
  // Nature & Landscapes (11-20)
  "A waterfall cascading into a misty tropical pool",
  "Northern lights dancing over a frozen lake in Iceland",
  "A thunderstorm rolling across vast golden wheat fields",
  "Cherry blossom petals falling gently on a quiet stream in Japan",
  "A volcano erupting with flowing lava at night",
  "Ocean waves crashing on dramatic cliff coastline",
  "A misty bamboo forest with sunbeams breaking through",
  "A timelapse of a desert sunset with shifting sand dunes",
  "Rain falling on a still pond creating ripple patterns",
  "A coral reef teeming with colorful fish swimming around",
  // Sci-Fi & Fantasy (21-30)
  "A spaceship flying through a colorful nebula in deep space",
  "A dragon soaring through stormy clouds breathing fire",
  "A futuristic neon city at night with flying cars",
  "A phoenix rising from golden flames into the sky",
  "An astronaut floating in space with Earth in background",
  "A magical portal opening in an enchanted forest",
  "A robot walking through a field of flowers discovering nature",
  "A cyberpunk street at night with neon signs and rain",
  "A castle floating in the sky above the clouds at sunset",
  "A space station orbiting a giant ringed planet",
  // Action & Dynamic (31-40)
  "A surfer riding a massive wave in slow motion",
  "A cheetah sprinting across the African savanna",
  "A fighter jet flying through a canyon at high speed",
  "A samurai drawing a katana in cherry blossom rain",
  "A snowboarder doing a backflip off a snowy mountain cliff",
  "Lightning striking a lone tree on an open plain at night",
  "A racing car drifting around a corner with smoke trails",
  "A martial artist performing a spinning kick in slow motion",
  "An eagle diving down to catch a fish from a river",
  "A meteor shower streaking across a starry night sky",
  // Cinematic & Moody (41-50)
  "A lone figure walking through fog on a cobblestone street at night",
  "A candle flickering in a dark Gothic cathedral",
  "A vintage train moving through a snowy mountain pass",
  "A geisha walking through a rainy Kyoto alley at twilight",
  "A lighthouse beam cutting through a stormy sea at night",
  "A pianist playing in an abandoned grand hall with dust particles floating",
  "A ship sailing through a massive ocean storm with huge waves",
  "Fireflies glowing in a dark enchanted forest at midnight",
  "A hot air balloon floating over misty valleys at sunrise",
  "A dancer performing ballet in a field of fireflies at dusk",
];

module.exports = { PROMPTS, VIDEO_PROMPTS };
